{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  production: "false"
  staging: "true"
  dev: "false"
  mainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  geoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/Nebula"
  lyraBaseURL: "https://swn-lyra-dev.azurewebsites.net"
  Auth0_Domain: "{{ .Values.global.env.auth0Domain }}"
  Auth0_ClientID: "{{ .Values.global.env.auth0ClientId }}"
  Auth0_Audience: "{{ .Values.global.env.auth0Audience }}"
{{ end }}
