//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[BackboneSegment] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class BackboneSegmentDto
    {
        public int BackboneSegmentID { get; set; }
        public int CatchIDN { get; set; }
        public BackboneSegmentTypeDto BackboneSegmentType { get; set; }
        public int? DownstreamBackboneSegmentID { get; set; }
        public string StreamName { get; set; }
    }

    public partial class BackboneSegmentSimpleDto
    {
        public int BackboneSegmentID { get; set; }
        public int CatchIDN { get; set; }
        public System.Int32 BackboneSegmentTypeID { get; set; }
        public int? DownstreamBackboneSegmentID { get; set; }
        public string StreamName { get; set; }
    }

}