//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[BackboneSegmentType] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class BackboneSegmentTypeDto
    {
        public int BackboneSegmentTypeID { get; set; }
        public string BackboneSegmentTypeName { get; set; }
        public string BackboneSegmentTypeDisplayName { get; set; }
    }

    public partial class BackboneSegmentTypeSimpleDto
    {
        public int BackboneSegmentTypeID { get; set; }
        public string BackboneSegmentTypeName { get; set; }
        public string BackboneSegmentTypeDisplayName { get; set; }
    }

}