//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[CustomPage] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class CustomPageDto
    {
        public int CustomPageID { get; set; }
        public string CustomPageDisplayName { get; set; }
        public string CustomPageVanityUrl { get; set; }
        public string CustomPageContent { get; set; }
        public MenuItemDto MenuItem { get; set; }
        public int? SortOrder { get; set; }
    }

    public partial class CustomPageSimpleDto
    {
        public int CustomPageID { get; set; }
        public string CustomPageDisplayName { get; set; }
        public string CustomPageVanityUrl { get; set; }
        public string CustomPageContent { get; set; }
        public System.Int32 MenuItemID { get; set; }
        public int? SortOrder { get; set; }
    }

}