//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[CustomRichTextType] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class CustomRichTextTypeDto
    {
        public int CustomRichTextTypeID { get; set; }
        public string CustomRichTextTypeName { get; set; }
        public string CustomRichTextTypeDisplayName { get; set; }
    }

    public partial class CustomRichTextTypeSimpleDto
    {
        public int CustomRichTextTypeID { get; set; }
        public string CustomRichTextTypeName { get; set; }
        public string CustomRichTextTypeDisplayName { get; set; }
    }

}