//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[CustomPageRole] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class CustomPageRoleDto
    {
        public int CustomPageRoleID { get; set; }
        public CustomPageDto CustomPage { get; set; }
        public RoleDto Role { get; set; }
    }

    public partial class CustomPageRoleSimpleDto
    {
        public int CustomPageRoleID { get; set; }
        public System.Int32 CustomPageID { get; set; }
        public System.Int32 RoleID { get; set; }
    }

}