//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[FieldDefinitionType] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class FieldDefinitionTypeDto
    {
        public int FieldDefinitionTypeID { get; set; }
        public string FieldDefinitionTypeName { get; set; }
        public string FieldDefinitionTypeDisplayName { get; set; }
    }

    public partial class FieldDefinitionTypeSimpleDto
    {
        public int FieldDefinitionTypeID { get; set; }
        public string FieldDefinitionTypeName { get; set; }
        public string FieldDefinitionTypeDisplayName { get; set; }
    }

}