//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[FieldDefinition] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class FieldDefinitionDto
    {
        public int FieldDefinitionID { get; set; }
        public FieldDefinitionTypeDto FieldDefinitionType { get; set; }
        public string FieldDefinitionValue { get; set; }
    }

    public partial class FieldDefinitionSimpleDto
    {
        public int FieldDefinitionID { get; set; }
        public System.Int32 FieldDefinitionTypeID { get; set; }
        public string FieldDefinitionValue { get; set; }
    }

}