//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[MenuItem] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class MenuItemDto
    {
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDisplayName { get; set; }
    }

    public partial class MenuItemSimpleDto
    {
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDisplayName { get; set; }
    }

}