//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[RegionalSubbasin] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class RegionalSubbasinDto
    {
        public int RegionalSubbasinID { get; set; }
        public string DrainID { get; set; }
        public string Watershed { get; set; }
        public int OCSurveyCatchmentID { get; set; }
        public int? OCSurveyDownstreamCatchmentID { get; set; }
        public DateTime? LastUpdate { get; set; }
    }

    public partial class RegionalSubbasinSimpleDto
    {
        public int RegionalSubbasinID { get; set; }
        public string DrainID { get; set; }
        public string Watershed { get; set; }
        public int OCSurveyCatchmentID { get; set; }
        public int? OCSurveyDownstreamCatchmentID { get; set; }
        public DateTime? LastUpdate { get; set; }
    }

}