//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[Role] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class RoleDto
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDisplayName { get; set; }
        public string RoleDescription { get; set; }
        public int SortOrder { get; set; }
    }

    public partial class RoleSimpleDto
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDisplayName { get; set; }
        public string RoleDescription { get; set; }
        public int SortOrder { get; set; }
    }

}