//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[User] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class UserDto
    {
        public int UserID { get; set; }
        public Guid? LegacyUserGuid { get; set; }
        public string GlobalUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public RoleDto Role { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public DateTime? DisclaimerAcknowledgedDate { get; set; }
        public bool IsActive { get; set; }
        public bool ReceiveSupportEmails { get; set; }
        public string LoginName { get; set; }
        public string Company { get; set; }
    }

    public partial class UserSimpleDto
    {
        public int UserID { get; set; }
        public Guid? LegacyUserGuid { get; set; }
        public string GlobalUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.Int32 RoleID { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public DateTime? DisclaimerAcknowledgedDate { get; set; }
        public bool IsActive { get; set; }
        public bool ReceiveSupportEmails { get; set; }
        public string LoginName { get; set; }
        public string Company { get; set; }
    }

}