//  HAND-MAINTAINED. This DTO used to be generated by efcorepocogenerator,
//  which no longer emits C# DTOs (it dropped --api-models-output-dir).
//  Keep it in sync with [dbo].[Watershed] by hand when the schema changes.
using System;


namespace Nebula.Models.DataTransferObjects
{
    public partial class WatershedDto
    {
        public int WatershedID { get; set; }
        public string WatershedName { get; set; }
    }

    public partial class WatershedSimpleDto
    {
        public int WatershedID { get; set; }
        public string WatershedName { get; set; }
    }

}